
# Set the docker image version and tag
image:
  repository: chr1st1anh/bitcoind
  tag: 22.0
  digest: sha256:cae7d6fc598d0e0e6cb7fba1dd3507f569d7b84f2661de23e3b4fa5efc586d46
  pullPolicy: IfNotPresent

# bitcoin.conf configuration file
configuration:
  rpcuser: bitcoindrpc
  txindex: 1
  rpcbind: 0.0.0.0
  rpcallowip: 0.0.0.0/0
  server: 1
  #can be any of mainnet, regtest, signet or testnet, if omitted mainnet will be used only a single network per deployment is supported
  network: regtest

# service
service:
  rpcPort: 8332
  p2pPort: 8333
  zmqBlock: 28332
  zmqTx: 28333

# persistent volume settings
persistence:
  accessMode: ReadWriteOnce
  size: 600G
  storageClass: gp2

# resources that the pod is allowed to consume
resources:
  requests:
    cpu: 250m
    memory: 1G
  limits:
    cpu: 250m
    memory: 1G