
# Set the docker image version and tag
image:
  repository: chr1st1anh/bitcoind
  tag: 22.0
  digest: sha256:cae7d6fc598d0e0e6cb7fba1dd3507f569d7b84f2661de23e3b4fa5efc586d46
  pullPolicy: IfNotPresent

# bitcoin.conf configuration file
configuration:
  rpcuser: #optional, if not quoted it will be generated
  txindex: 0
  server: 1
  network: mainnet #can be any of mainnet, regtest, signet or testnet, if omitted mainnet will be used only a single network per deployment is supported
  prune: 12000 #Reduce storage requirements by enabling pruning (deleting) of old blocks. This allows the pruneblockchain RPC to be called to delete specific blocks, and enables automatic pruning of old blocks if a target size in MiB is provided. This mode is incompatible with -txindex and -rescan. Warning: Reverting this setting requires re-downloading the entire blockchain. (default: 0 = disable pruning blocks, 1 = allow manual pruning via RPC, 550 = automatically prune block files to stay under the specified target size in MiB)
  passwordLength: 50 #the rpc password length
  rpcallowip: 0.0.0.0/0 #use the cluster private ip range to further restrict connection attempts

# persistent volume settings
persistence:
  accessMode: ReadWriteOnce
  size: 14G
  storageClass: gp2

# resources that the pod is allowed to consume
resources:
  requests:
    cpu: 250m
    memory: 1G
  limits:
    cpu: 250m
    memory: 1G