apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoind.name" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data: 
  bitcoin.conf: |
    {{ include "network" . }}=1
    [{{ include "network" . }}]
    zmqpubrawblock=tcp://0.0.0.0:28332
    zmqpubrawtx=tcp://0.0.0.0:28333
    txindex={{ .Values.configuration.txindex }}
    # server=1 tells Bitcoin-Qt and bitcoind to accept JSON-RPC commands
    server={{ .Values.configuration.server }}
    rpcbind=0.0.0.0 #this is restricted from within the cluster
    rpcallowip=0.0.0.0/0 #this is restricted from within the cluster
    # Print to console (stdout) so that "docker logs bitcoind" prints useful
    # information.
    printtoconsole={{ .Values.configuration.printtoconsole | default 1 }}
    # We probably don't want a wallet.
    disablewallet={{ .Values.configuration.disablewallet | default 1 }}
    prune={{ .Values.configuration.prune | default 0 }}