apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitcoind.name" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Release.IsInstall }}
  rpcpassword: {{ randAlphaNum .Values.configuration.passwordLength | b64enc }}
  {{ else }}
  # `index` function is necessary because the property name contains a dash.
  # Otherwise (...).data.db_password would have worked too.
  rpcpassword:  {{ index (lookup "v1" "Secret" .Release.Namespace "bitcoind").data "rpcpassword" }}
  {{ end }}
  {{- if .Release.IsInstall }}
  rpcuser: {{ .Values.configuration.rpcuser | default randAlphaNum 8 | b64enc }}
  {{ else }}
    {{ if (.Values.configuration.rpcuser) }} 
  rpcuser:  {{ .Values.configuration.rpcuser | b64enc}}
    {{ else }}
  rpcuser:  {{ index (lookup "v1" "Secret" .Release.Namespace "bitcoind").data "rpcpassword" }}
    {{ end }}
  {{ end }}